// <auto-generated />
using System;
using INTEX2_group1_3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace INTEX2_group1_3.Migrations.TheMummyProject
{
    [DbContext(typeof(TheMummyProjectContext))]
    [Migration("20230414061706_AppUpdate32")]
    partial class AppUpdate32
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.excelimporter$template_nr_mxseq", "'excelimporter$template_nr_mxseq', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.system$filedocument_fileid_mxseq", "'system$filedocument_fileid_mxseq', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.system$queuedtask_sequence_mxseq", "'system$queuedtask_sequence_mxseq', '', '1', '1', '', '', 'Int64', 'False'");

            modelBuilder.Entity("INTEX2_group1_3.Models.Analysis", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Analysisid")
                        .HasColumnName("analysisid")
                        .HasColumnType("integer");

                    b.Property<int?>("Analysistype")
                        .HasColumnName("analysistype")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Doneby")
                        .IsRequired()
                        .HasColumnName("doneby")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("analysis");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AnalysisTextile", b =>
                {
                    b.Property<long>("MainAnalysisid")
                        .HasColumnName("main$analysisid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainAnalysisid", "MainTextileid")
                        .HasName("main$analysis_textile_pkey");

                    b.HasIndex("MainTextileid", "MainAnalysisid")
                        .HasName("idx_main$analysis_textile_main$textile_main$analysis");

                    b.ToTable("analysis_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Artifactfagelgamousregister", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Coordinateset")
                        .IsRequired()
                        .HasColumnName("coordinateset")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnName("notes")
                        .HasColumnType("text");

                    b.Property<string>("Photographed")
                        .IsRequired()
                        .HasColumnName("photographed")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Registernum")
                        .IsRequired()
                        .HasColumnName("registernum")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("artifactfagelgamousregister");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.ArtifactfagelgamousregisterBurialmain", b =>
                {
                    b.Property<long>("MainArtifactfagelgamousregisterid")
                        .HasColumnName("main$artifactfagelgamousregisterid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.HasKey("MainArtifactfagelgamousregisterid", "MainBurialmainid")
                        .HasName("main$artifactfagelgamousregister_burialmain_pkey");

                    b.HasIndex("MainBurialmainid", "MainArtifactfagelgamousregisterid")
                        .HasName("idx_main$artifactfagelgamousregister_burialmain");

                    b.ToTable("artifactfagelgamousregister_burialmain");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Artifactkomaushimregister", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Currentlocation")
                        .IsRequired()
                        .HasColumnName("currentlocation")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnName("date")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnName("dimensions")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Entrydate")
                        .HasColumnName("entrydate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excavatornum")
                        .IsRequired()
                        .HasColumnName("excavatornum")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Finder")
                        .IsRequired()
                        .HasColumnName("finder")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnName("material")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnName("number")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnName("photos")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnName("position")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnName("provenance")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Qualityphotos")
                        .IsRequired()
                        .HasColumnName("qualityphotos")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Rehousedto")
                        .IsRequired()
                        .HasColumnName("rehousedto")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnName("remarks")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("artifactkomaushimregister");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.ArtifactkomaushimregisterBurialmain", b =>
                {
                    b.Property<long>("MainArtifactkomaushimregisterid")
                        .HasColumnName("main$artifactkomaushimregisterid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.HasKey("MainArtifactkomaushimregisterid", "MainBurialmainid")
                        .HasName("main$artifactqumoshimregistrar_burialmain_pkey");

                    b.HasIndex("MainBurialmainid", "MainArtifactkomaushimregisterid")
                        .HasName("idx_main$artifactkomaushimregister_burialmain");

                    b.ToTable("artifactkomaushimregister_burialmain");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetRoleClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserLogins", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserRoles", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Biological", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Bagnumber")
                        .HasColumnName("bagnumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Clusternumber")
                        .HasColumnName("clusternumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnName("initials")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnName("notes")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Previouslysampled")
                        .IsRequired()
                        .HasColumnName("previouslysampled")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("Racknumber")
                        .HasColumnName("racknumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("biological");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.BiologicalC14", b =>
                {
                    b.Property<long>("MainBiologicalid")
                        .HasColumnName("main$biologicalid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainC14id")
                        .HasColumnName("main$c14id")
                        .HasColumnType("bigint");

                    b.HasKey("MainBiologicalid", "MainC14id")
                        .HasName("main$biological_c14_pkey");

                    b.HasIndex("MainC14id", "MainBiologicalid")
                        .HasName("idx_main$biological_c14_main$c14_main$biological");

                    b.ToTable("biological_c14");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Bodyanalysischart", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("CariesPeriodontalDisease")
                        .HasColumnName("Caries_Periodontal_Disease")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("DorsalPittingBoolean")
                        .HasColumnName("DorsalPitting (boolean)")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EstimateStature")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Femur")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FemurHeadDiameter")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<double?>("FemurLength")
                        .HasColumnType("double precision");

                    b.Property<string>("Gonion")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Humerus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("HumerusHeadDiameter")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<double?>("HumerusLength")
                        .HasColumnType("double precision");

                    b.Property<string>("LamboidSuture")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MedialIpRamus")
                        .HasColumnName("Medial_IP_Ramus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Notes")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("NuchalCrest")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Observations")
                        .HasColumnType("character varying(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("OrbitEdge")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Osteophytosis")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ParietalBossing")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PreauricularSulcusBoolean")
                        .HasColumnName("PreauricularSulcus (Boolean)")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<long?>("Preservationindex")
                        .HasColumnName("preservationindex")
                        .HasColumnType("bigint");

                    b.Property<string>("PubicBone")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Robust")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("SciaticNotch")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SphenooccipitalSynchrondrosis")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SquamosSuture")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SubpubicAngle")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SupraorbitalRidges")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ToothAttrition")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ToothEruption")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ToothEruptionAgeEstimate")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("VentralArc")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("ZygomaticCrest")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("bodyanalysischart");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Books", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("author")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnName("link")
                        .HasColumnType("character varying(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("books");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Burialmain", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Adultsubadult")
                        .HasColumnName("adultsubadult")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Ageatdeath")
                        .HasColumnName("ageatdeath")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Area")
                        .HasColumnName("area")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<long?>("Burialid")
                        .HasColumnName("burialid")
                        .HasColumnType("bigint");

                    b.Property<string>("Burialmaterials")
                        .HasColumnName("burialmaterials")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Burialnumber")
                        .HasColumnName("burialnumber")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Clusternumber")
                        .HasColumnName("clusternumber")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Dataexpertinitials")
                        .HasColumnName("dataexpertinitials")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Dateofexcavation")
                        .HasColumnName("dateofexcavation")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Depth")
                        .HasColumnName("depth")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Eastwest")
                        .HasColumnName("eastwest")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Excavationrecorder")
                        .HasColumnName("excavationrecorder")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Facebundles")
                        .HasColumnName("facebundles")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Fieldbookexcavationyear")
                        .HasColumnName("fieldbookexcavationyear")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Fieldbookpage")
                        .HasColumnName("fieldbookpage")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Goods")
                        .HasColumnName("goods")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Hair")
                        .HasColumnName("hair")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Haircolor")
                        .HasColumnName("haircolor")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Headdirection")
                        .HasColumnName("headdirection")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Length")
                        .HasColumnName("length")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Northsouth")
                        .HasColumnName("northsouth")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Photos")
                        .HasColumnName("photos")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Preservation")
                        .HasColumnName("preservation")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Samplescollected")
                        .HasColumnName("samplescollected")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Shaftnumber")
                        .HasColumnName("shaftnumber")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Southtofeet")
                        .HasColumnName("southtofeet")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Southtohead")
                        .HasColumnName("southtohead")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Squareeastwest")
                        .HasColumnName("squareeastwest")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Squarenorthsouth")
                        .HasColumnName("squarenorthsouth")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Westtofeet")
                        .HasColumnName("westtofeet")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Westtohead")
                        .HasColumnName("westtohead")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Wrapping")
                        .HasColumnName("wrapping")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("burialmain");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.BurialmainBiological", b =>
                {
                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainBiologicalid")
                        .HasColumnName("main$biologicalid")
                        .HasColumnType("bigint");

                    b.HasKey("MainBurialmainid", "MainBiologicalid")
                        .HasName("main$burialmain_biological_pkey");

                    b.HasIndex("MainBiologicalid", "MainBurialmainid")
                        .HasName("idx_main$burialmain_biological_main$biological_main$burialmain");

                    b.ToTable("burialmain_biological");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.BurialmainBodyanalysischart", b =>
                {
                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainBodyanalysischartid")
                        .HasColumnName("main$bodyanalysischartid")
                        .HasColumnType("bigint");

                    b.HasKey("MainBurialmainid", "MainBodyanalysischartid")
                        .HasName("main$burialmain_bodyanalysischart_pkey");

                    b.HasIndex("MainBodyanalysischartid", "MainBurialmainid")
                        .HasName("idx_main$burialmain_bodyanalysischart");

                    b.ToTable("burialmain_bodyanalysischart");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.BurialmainCranium", b =>
                {
                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainCraniumid")
                        .HasColumnName("main$craniumid")
                        .HasColumnType("bigint");

                    b.HasKey("MainBurialmainid", "MainCraniumid")
                        .HasName("main$burialmain_cranium_pkey");

                    b.HasIndex("MainCraniumid", "MainBurialmainid")
                        .HasName("idx_main$burialmain_cranium_main$cranium_main$burialmain");

                    b.ToTable("burialmain_cranium");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.BurialmainTextile", b =>
                {
                    b.Property<long>("MainBurialmainid")
                        .HasColumnName("main$burialmainid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainBurialmainid", "MainTextileid")
                        .HasName("main$burialmain_textile_pkey");

                    b.HasIndex("MainTextileid", "MainBurialmainid")
                        .HasName("idx_main$burialmain_textile_main$textile_main$burialmain");

                    b.ToTable("burialmain_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.C14", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Agebp")
                        .HasColumnName("agebp")
                        .HasColumnType("integer");

                    b.Property<string>("C14lab")
                        .IsRequired()
                        .HasColumnName("c14lab")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("Calendardate")
                        .HasColumnName("calendardate")
                        .HasColumnType("integer");

                    b.Property<int?>("Calibrateddateavg")
                        .HasColumnName("calibrateddateavg")
                        .HasColumnType("integer");

                    b.Property<int?>("Calibrateddatemax")
                        .HasColumnName("calibrateddatemax")
                        .HasColumnType("integer");

                    b.Property<int?>("Calibrateddatemin")
                        .HasColumnName("calibrateddatemin")
                        .HasColumnType("integer");

                    b.Property<int?>("Calibratedspan")
                        .HasColumnName("calibratedspan")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnName("category")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Foci")
                        .IsRequired()
                        .HasColumnName("foci")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnName("location")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnName("questions")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<int?>("Rack")
                        .HasColumnName("rack")
                        .HasColumnType("integer");

                    b.Property<int?>("Size")
                        .HasColumnName("size")
                        .HasColumnType("integer");

                    b.Property<int?>("Tubenumber")
                        .HasColumnName("tubenumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("c14");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Color", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Colorid")
                        .HasColumnName("colorid")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("color");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.ColorTextile", b =>
                {
                    b.Property<long>("MainColorid")
                        .HasColumnName("main$colorid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainColorid", "MainTextileid")
                        .HasName("main$color_textile_pkey");

                    b.HasIndex("MainTextileid", "MainColorid")
                        .HasName("idx_main$color_textile_main$textile_main$color");

                    b.ToTable("color_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Cranium", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("AlphaCore")
                        .HasColumnName("alpha_core")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("BasionBregmaHeight")
                        .HasColumnName("basion_bregma_height")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("BasionNasion")
                        .HasColumnName("basion_nasion")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("BasionProsthionLength")
                        .HasColumnName("basion_prosthion_length")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("BizygomaticDiameter")
                        .HasColumnName("bizygomatic_diameter")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("InterobitalBreadth")
                        .HasColumnName("interobital_breadth")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("InterorbitalBreadth")
                        .HasColumnName("interorbital_breadth")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("InterorbitalSubtense")
                        .HasColumnName("interorbital_subtense")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("MaxNasalBreadth")
                        .HasColumnName("max_nasal_breadth")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("Maxcraniumbreadth")
                        .HasColumnName("maxcraniumbreadth")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("Maxcraniumlength")
                        .HasColumnName("maxcraniumlength")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("MidOrbitalBreadth")
                        .HasColumnName("mid_orbital_breadth")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("MidOrbitalSubtense")
                        .HasColumnName("mid_orbital_subtense")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("NasionProsthionUpper")
                        .HasColumnName("nasion_prosthion_upper")
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("NasoAlphaSubtense")
                        .HasColumnName("naso_alpha__subtense")
                        .HasColumnType("numeric(28,8)");

                    b.HasKey("Id");

                    b.ToTable("cranium");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Decoration", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Decorationid")
                        .HasColumnName("decorationid")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("decoration");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.DecorationTextile", b =>
                {
                    b.Property<long>("MainDecorationid")
                        .HasColumnName("main$decorationid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainDecorationid", "MainTextileid")
                        .HasName("main$decoration_textile_pkey");

                    b.HasIndex("MainTextileid", "MainDecorationid")
                        .HasName("idx_main$decoration_textile_main$textile_main$decoration");

                    b.ToTable("decoration_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Dimension", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Dimensionid")
                        .HasColumnName("dimensionid")
                        .HasColumnType("integer");

                    b.Property<string>("Dimensiontype")
                        .IsRequired()
                        .HasColumnName("dimensiontype")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("dimension");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.DimensionTextile", b =>
                {
                    b.Property<long>("MainDimensionid")
                        .HasColumnName("main$dimensionid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainDimensionid", "MainTextileid")
                        .HasName("main$dimension_textile_pkey");

                    b.HasIndex("MainTextileid", "MainDimensionid")
                        .HasName("idx_main$dimension_textile_main$textile_main$dimension");

                    b.ToTable("dimension_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Newsarticle", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("author")
                        .HasColumnType("character varying");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("character varying");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("character varying");

                    b.Property<string>("Urltoimage")
                        .IsRequired()
                        .HasColumnName("urltoimage")
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("newsarticle");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Photodata", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnName("filename")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("Photodataid")
                        .HasColumnName("photodataid")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("photodata");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.PhotodataTextile", b =>
                {
                    b.Property<long>("MainPhotodataid")
                        .HasColumnName("main$photodataid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainPhotodataid", "MainTextileid")
                        .HasName("main$photodata_textile_pkey");

                    b.HasIndex("MainTextileid", "MainPhotodataid")
                        .HasName("idx_main$photodata_textile_main$textile_main$photodata");

                    b.ToTable("photodata_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Photoform", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnName("area")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Burialnumber")
                        .IsRequired()
                        .HasColumnName("burialnumber")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Eastwest")
                        .IsRequired()
                        .HasColumnName("eastwest")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnName("filename")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Northsouth")
                        .IsRequired()
                        .HasColumnName("northsouth")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<DateTime?>("Photodate")
                        .HasColumnName("photodate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Photographer")
                        .IsRequired()
                        .HasColumnName("photographer")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Squareeastwest")
                        .IsRequired()
                        .HasColumnName("squareeastwest")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Squarenorthsouth")
                        .IsRequired()
                        .HasColumnName("squarenorthsouth")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Tableassociation")
                        .IsRequired()
                        .HasColumnName("tableassociation")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("photoform");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Structure", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Structureid")
                        .HasColumnName("structureid")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("structure");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.StructureTextile", b =>
                {
                    b.Property<long>("MainStructureid")
                        .HasColumnName("main$structureid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainStructureid", "MainTextileid")
                        .HasName("main$structure_textile_pkey");

                    b.HasIndex("MainTextileid", "MainStructureid")
                        .HasName("idx_main$structure_textile_main$textile_main$structure");

                    b.ToTable("structure_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Teammember", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnName("bio")
                        .HasColumnType("character varying");

                    b.Property<string>("Membername")
                        .IsRequired()
                        .HasColumnName("membername")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("teammember");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Textile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Burialnumber")
                        .HasColumnName("burialnumber")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying");

                    b.Property<string>("Direction")
                        .HasColumnName("direction")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Estimatedperiod")
                        .HasColumnName("estimatedperiod")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Locale")
                        .HasColumnName("locale")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Photographeddate")
                        .HasColumnName("photographeddate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Sampledate")
                        .HasColumnName("sampledate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Textileid")
                        .HasColumnName("textileid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Textilefunction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<int?>("Textilefunctionid")
                        .HasColumnName("textilefunctionid")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("textilefunction");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.TextilefunctionTextile", b =>
                {
                    b.Property<long>("MainTextilefunctionid")
                        .HasColumnName("main$textilefunctionid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainTextilefunctionid", "MainTextileid")
                        .HasName("main$textilefunction_textile_pkey");

                    b.HasIndex("MainTextileid", "MainTextilefunctionid")
                        .HasName("idx_main$textilefunction_textile");

                    b.ToTable("textilefunction_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.Yarnmanipulation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Angle")
                        .IsRequired()
                        .HasColumnName("angle")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnName("component")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasColumnName("count")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnName("direction")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Manipulation")
                        .IsRequired()
                        .HasColumnName("manipulation")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnName("material")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Ply")
                        .IsRequired()
                        .HasColumnName("ply")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Thickness")
                        .IsRequired()
                        .HasColumnName("thickness")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("Yarnmanipulationid")
                        .HasColumnName("yarnmanipulationid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("yarnmanipulation");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.YarnmanipulationTextile", b =>
                {
                    b.Property<long>("MainYarnmanipulationid")
                        .HasColumnName("main$yarnmanipulationid")
                        .HasColumnType("bigint");

                    b.Property<long>("MainTextileid")
                        .HasColumnName("main$textileid")
                        .HasColumnType("bigint");

                    b.HasKey("MainYarnmanipulationid", "MainTextileid")
                        .HasName("main$yarnmanipulation_textile_pkey");

                    b.HasIndex("MainTextileid", "MainYarnmanipulationid")
                        .HasName("idx_main$yarnmanipulation_textile");

                    b.ToTable("yarnmanipulation_textile");
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetRoleClaims", b =>
                {
                    b.HasOne("INTEX2_group1_3.Models.AspNetRoles", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserClaims", b =>
                {
                    b.HasOne("INTEX2_group1_3.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserLogins", b =>
                {
                    b.HasOne("INTEX2_group1_3.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserRoles", b =>
                {
                    b.HasOne("INTEX2_group1_3.Models.AspNetRoles", "Role")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEX2_group1_3.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INTEX2_group1_3.Models.AspNetUserTokens", b =>
                {
                    b.HasOne("INTEX2_group1_3.Models.AspNetUsers", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
